# Tokengen Docker file
FROM golang:latest as builder

ENV GO111MODULE=on

WORKDIR /config
WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make tokengen

# final stage
FROM scratch
COPY --from=builder /app/cmd/tokengen/tokengen /app/
COPY --from=builder /app/Configuration.json /config/
ENTRYPOINT ["/app/tokengen", "-config", "/config/Configuration.json"]